apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: auth-backend
  name: auth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: auth-backend
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password123
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://auth-db:3306/journalauth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: journalauth_user
          image: osama251/journalauth-backend:latest
          imagePullPolicy: IfNotPresent
          name: journalauth-backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
