apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: logs-db
  name: logs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logs-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: logs-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: journallogs
            - name: MYSQL_PASSWORD
              value: password123
            - name: MYSQL_ROOT_PASSWORD
              value: 12345AbcD
            - name: MYSQL_USER
              value: journallogs_user
          image: mysql:8.0
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h localhost -uroot -p12345AbcD || exit 1
            failureThreshold: 20
            periodSeconds: 5
            timeoutSeconds: 3
          name: journallogs-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-logs-data
      restartPolicy: Always
      volumes:
        - name: mysql-logs-data
          persistentVolumeClaim:
            claimName: mysql-logs-data
