apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: logs-backend
  name: logs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logs-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: logs-backend
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password123
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://logs-db:3306/journallogs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: journallogs_user
          image: osama251/journallogs-backend:latest
          imagePullPolicy: IfNotPresent
          name: journallogs-backend
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
